dataset:
  name: "PureMarketFoundationModelDataset"
  version: "1.0.0"
  schema_version: "v1"
  default_symbols:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
  default_market: "futures"
  snapshot_date: "2026-07-30"
  train_symbols:
    - BTCUSDT
    - ETHUSDT
  val_symbols:
    - SOLUSDT
  test_symbols:
    - BTCUSDT
    - ETHUSDT
  train_end_date: "2024-11-30"
